### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by boasist** [nebhead/spkr-select#1]
I installed manually, omitting the IR portion, and then was greeted with a bad gateway issue. For convenience, I then ran the install file and after a reboot the web interface works great now. A schematic would be the most help now going forward. Thank you.

**Comment by nebhead** [comment]
Yep, I definitely need to get on the schematic.  It's been on the back-burner for a while with other projects.  Glad you got it to work - I'll probably need to fix-up the documentation so that the manual install works properly as well it seems.  I have some upgrades coming for this project as well, such as controlling via IFTTT (so that you can use Google Assistant and/or Alexa).  Thanks for the heads up!

**Comment by boasist** [comment]
I've been using this as a guide, yet I'm not getting any switching on the relays. I'm using a pi 3 B, I could have to add in the resistors as mentioned [https://docs.google.com/file/d/0B5-HND9HJkXWSTQtYlFTZ3VyODA/edit](url)

I'm using GPIO 17 and 22, and those are connected to relay 1 and 2. I get a weak light on 22, and a full light on 17. Yet switching the speakers on the web interface doesn't do anything.

GPIO.setup(17, GPIO.OUT) # LED 01 - Speakers 1
GPIO.setup(18, GPIO.OUT) # LED 02 - Speakers 2
GPIO.setup(19, GPIO.OUT) # LED 03 - Speakers 3
#GPIO.setup(20, GPIO.OUT) # LED 04 - Not used / connected currently
GPIO.setup(21, GPIO.OUT) # LED 05 - Protection

GPIO.setup(22, GPIO.OUT, initial=0) # Relays (1 & 2) - Speakers 1 (L/R)
GPIO.setup(23, GPIO.OUT, initial=1) # Relays (3 & 4) - Speakers 2 (L/R)
GPIO.setup(24, GPIO.OUT, initial=1) # Relays (5 & 6) - Speakers 3 (L/R)
GPIO.setup(25, GPIO.OUT, initial=1) # Relays (7 & 8) - Protection (L/R)

**Comment by nebhead** [comment]
Sorry!  I think this may be a case where I definitely need to get my documentation updated.  The reason I had the GPIO22 logic swapped was due to some comments that leaving a relay in activated position for extended periods of time, would cause it to wear out faster.  I'm not actually sure if this is true or not, but I reversed the logic for the first set of relays for the speakers because these are my living room speakers which are always on.  Typically it's the other speakers that are normally off and would be occasionally switched on and used.  I hope that helps and I promise that I will start working on that schematic so it's easier to see what I'm talking about.

**Comment by boasist** [comment]
Ahh OK, I'll move those around then. But yes, the schematic holds the key to all of this. Thank you!

**Comment by boasist** [comment]
I bought a pi zero WH as it was only $6, got the setup all done.

Pickle doesn't pull still, errors on finding the distro
The install file fails as well now with the addition of the certificate

I got it all working from the web perspective, but I still get nothing when testing on the relay board. Thank you for adding the extra information to the readme. I'd be willing to help in any way needed.

I'm trying to test on the relay board itself before I start soldering.

Thank you.

**Comment by nebhead** [comment]
Hang in there!  I have an update coming tonight with the full schematics and some bug fixes to boot.  I think one of the issues you might have been experiencing was that when installing without lirc (for the IR Remote Control feature) or the lirc-python module, the control.py script may actually fail.  I'm going to my fixes a try on my own setup tonight and then push the changes to GitHub.  Regardless - schematics are inbound.  :)  

Not sure about Pickle not installing... I might have to try to figure that one out.  I'm assuming you're connected via a USB network device of some kind?  Maybe you can cut/paste the error message you're getting when the pickle pull fails?

**Comment by nebhead** [comment]
OK, pushed v2.0.1 with the schematics and minor updates to the control.py file.  Let me know how this works for you!  

Thanks!

**Comment by boasist** [comment]
This is excellent, I'll do an update tonight and try it out. 
Here is the pickle error...

`
pi@raspberrypi:~ $ sudo pip install pickle
Collecting pickle
  Could not find a version that satisfies the requirement pickle (from versions: )
No matching distribution found for pickle
`

**Comment by nebhead** [comment]
You know, it looks like pickle is included in python 2.7.13, so it doesn't really need to be installed.  (https://docs.python.org/2/py-modindex.html).  Thus, we can skip that step of doing a python pip install pickle.

**Comment by boasist** [comment]
Still a few errors on the listed install process.

`pi@raspberrypi:~ $ cd ~/spkr-select
pi@raspberrypi:~/spkr-select $ sudo rm /etc/nginx/sites-enabled/default
pi@raspberrypi:~/spkr-select $ sudo cp spkr-select.nginx /etc/nginx/sites-available/spkr-select
pi@raspberrypi:~/spkr-select $ sudo ln -s /etc/nginx/sites-available/spkr-select /etc/nginx/sites-enabled
pi@raspberrypi:~/spkr-select $ cd ~/spkr-select/certs
pi@raspberrypi:~/spkr-select/certs $ sudo .\generate.sh
sudo: .generate.sh: command not found
pi@raspberrypi:~/spkr-select/certs $ sudo service nginx restart
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
pi@raspberrypi:~/spkr-select/certs $ cd ~/spkr-select/certs
pi@raspberrypi:~/spkr-select/certs $ s $ cd ~/spkr-select/certs
-bash: s: command not found
pi@raspberrypi:~/spkr-select/certs $ s $ cd ~/spkr-select/certs
-bash: s: command not found
pi@raspberrypi:~/spkr-select/certs $ sudo ./generate.sh
sudo: ./generate.sh: command not found
pi@raspberrypi:~/spkr-select/certs $ cd ~/spkr-select/supervisor
pi@raspberrypi:~/spkr-select/supervisor $ sudo cp *.conf /etc/supervisor/conf.d/
pi@raspberrypi:~/spkr-select/supervisor $ sudo service supervisor start
pi@raspberrypi:~/spkr-select/supervisor $ sudo supervisorctl reread
ERROR: CANT_REREAD: The directory named as part of the path /home/pi/spkr-select/logs/control.out.log does not exist. in section 'program:control' (file: '/etc/supervisor/conf.d/control.conf')
pi@raspberrypi:~/spkr-select/supervisor $ sudo supervisorctl update
error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: The directory named as part of the path /home/pi/spkr-select/logs/control.out.log does not exist. in section 'program:control' (file: '/etc/supervisor/conf.d/control.conf')">: file: /usr/lib/python2.7/xmlrpclib.py line: 800
pi@raspberrypi:~/spkr-select/supervisor $ sudo reboot
`

**Comment by nebhead** [comment]
OK, let me grab a spare Pi and run through the process to see what's going on.  I think the generate script might not be executable (i.e. might need to do 'sudo chmod +x generate.sh').

**Comment by nebhead** [comment]
I think I have it figured out now.  I had multiple errors (so sorry!) in my install process.  

1. As noted earlier, no need to install Pickle via PIP.  It's already there in the current version of Python, so we can omit that line item.
2. Before executing the generate.sh script, we need to make it executable by running: 
    `sudo chmod +x generate.sh`
3. I mixed up a forward slash with a backslash when running the script.  It should be:
    `sudo ./generate.sh`
4. Supervisor get's upset that there is no log directory as defined in the configuration file.  It's there in my install because I had previously created it, but for some reason, directories that are empty don't get pushed by git by default.  So I'm going to put a text file in the log directory to force it to be created when cloning.  You can simply create it by doing to the following:
```
   cd ~/spkr-select
   mkdir logs
```
Once we have all these done, you should be able to `sudo reboot` and we should be in business!  

And that should be all we need to fix to get this up and running.  I'll make the changes in the README.md and push an update today.  

Additionally, I'm going to work on an auto-install script that can hopefully take care of almost all of these steps in an automated fashion.  Hopefully, that makes it completely error-proof to do from scratch.  

Last but not least, I wanted to thank you for your donation to the project!  That was beyond generous, so HUGE thank you to you.

**Comment by boasist** [comment]
You're quite welcome.

I'm flashing new and going to try the auto install now.

`*************************************************************************
**                                                                     **
**      Cloning Speaker-Select from GitHub...                          **
**                                                                     **
*************************************************************************
bash: line 77: git: command not found
*************************************************************************
**                                                                     **
**      Configuring nginx...                                           **
**                                                                     **
*************************************************************************
bash: line 87: cd: /home/pi/spkr-select: No such file or directory
rm: cannot remove '/etc/nginx/sites-enabled/default': No such file or directory
cp: cannot stat 'spkr-select.nginx': No such file or directory
ln: failed to create symbolic link '/etc/nginx/sites-enabled': No such file or directory
bash: line 100: cd: /home/pi/spkr-select/certs: No such file or directory
Received SIGHUP or SIGTERM

Buffer written to localhost.conf.save

`

**Comment by nebhead** [comment]
Hmm... looks like your apt install git failed.  Try running again and see if the dependencies installed properly.  I actually ran into the same problem when my network dropped during the script.

**Comment by boasist** [comment]
OK - I did that, then I got a error and it cancelled out around line 98 I believe. I then ran the install manually with the automated lines. All went well aside from a box size error on the supervisor confirmation. That covers the install.

A reboot and all is working well on the web interface and it's flipping the switches. Now it's time to solder!

**Comment by nebhead** [comment]
Nice!  Congrats - I hope it's smooth sailing from here on out.
